export enum FlightStatus {
  SCHEDULED = 'SCHEDULED',
  DELAYED = 'DELAYED',
  CANCELLED = 'CANCELLED',
  DEPARTED = 'DEPARTED',
  ARRIVED = 'ARRIVED',
  BOARDING = 'BOARDING',
  IN_FLIGHT = 'IN_FLIGHT',
}

export enum FlightClass {
  ECONOMY = 'ECONOMY',
  PREMIUM_ECONOMY = 'PREMIUM_ECONOMY',
  BUSINESS = 'BUSINESS',
  FIRST_CLASS = 'FIRST_CLASS',
}
